/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 ./public/models/basicchar_idle.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/basicchar_idle.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Roundcube001" position={[0, 2.197, 0]} />
        <group name="Armature" position={[0, 0.631, 0]}>
          <primitive object={nodes.Hips} />
          <skinnedMesh name="Roundcube" geometry={nodes.Roundcube.geometry} material={nodes.Roundcube.material} skeleton={nodes.Roundcube.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/basicchar_idle.glb')
