/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 ../public/models/untitled.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/untitled.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.215, -32.964, -0.228]} scale={0.315}>
        <mesh geometry={nodes.Mesh.geometry} material={materials.Material} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/untitled.glb')
